# -*- coding: utf-8 -*-
"""
Created on Fri May 29 10:08:11 2020

@author: pravesh
"""

import cv2
import numpy as np
import os
from os import listdir
from os.path import isfile,join
import random

cap = cv2.VideoCapture(0)

ret,frame1 = cap.read()
ret,frame2 = cap.read()

while cap.isOpened():
    diff=cv2.absdiff(frame1,frame2)
    gray = cv2.cvtColor(diff,cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray,(5,5),0)
    _,thresh = cv2.threshold(blur,20,255,cv2.THRESH_BINARY)
    dilated = cv2.dilate(thresh,None,iterations=3)
    contours,_=cv2.findContours(dilated,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    
    for contour in contours:
        (x,y,w,h)=cv2.boundingRect(contour)
        if cv2.contourArea(contour)<1000:
            continue
        cv2.rectangle(frame1,(x,y),(x+w , y+h),(0,255,0),2)
        cv2.putText(frame1,"Status:{}".format('Movement'),(10,20),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),3)
        music_dir="H:/song/warning" # make one folder which only contains music and give the full path of that folder here
        songs=listdir(music_dir)
        #print(songs)
        #os.startfile("H:/song/warning")
                                
        #print(len(songs))
                                # if you will see an "list index out of range" error then make sure that
                                #number of songs is less than that of random number generated by function.
        #ak=random.randint(0,len(songs))# for random song which is more attractive
        #print(ak)
        os.startfile(os.path.join(music_dir,songs[0]))
        print(songs[0])
        break # if you wanna control this loop then you can control this by assuming a variable and make the value is 0 or 1 with user interest.
                                     
    #cv2.drawContours(frame1,contours,-1,(0,255,0),2)
    
    
    cv2.imshow("feed",frame1)
    frame1=frame2
    ret,frame2=cap.read()
    
    if cv2.waitKey(40)==27:
        break
    
cap.release
cv2.destroyAllWindows()